---
- name: Verify
  hosts: localhost
  gather_facts: no

  tasks:
    - name: check if files exist
      stat:
        path: /tmp/wait_for_connection_succeeded.txt
      register: wait_for_connection_status

    - name: check if files exist
      stat:
        path: /tmp/become_succeeded.txt
      register: become_status

    - name: check results
      assert:
        that:
          - wait_for_connection_status.stat.exists
          - become_status.stat.exists
